In [36]:
import numpy as np
import pandas as pd
from functools import reduce

In [42]:
bakery = pd.read_csv("5000-out2.csv", names=np.arange(50))
bakery

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
1      0   0   0   0   1   1   1   0   0   0  ...   0   0   0   0   0   0   0   
2      0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   
3      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
5      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
4996   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
4997   1   0   1   0   0   0   1   0   0   0  ...   0   0   0   0   0   1   1   
4998   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   
4999   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
5000   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   1   0   

      47  48  49  
1      0   0   0  
2      1   0   0  
3      0   0   0  
4      0   0   0  
5      0   0   0  
...   ..  ..  ..  
4996   0   0   0  
4997   0   0   0  
4998   0   0   1  
4999   0   1   0  
5000   0   0   0  

[5000 rows x 50 columns]

In [50]:
sum(bakery[0] & bakery[1] & bakery[2] & bakery[3])

1

In [13]:
#sum(bakery[0])
support = np.array([sum(bakery[i]) for i in bakery.columns])
rsupport = support/len(bakery[0])

In [14]:
support

array([399, 425, 373, 418, 480, 438, 191, 554, 230, 409, 193, 391, 367,
       211, 391, 380, 426, 381, 460, 354, 222, 194, 477, 320, 321, 226,
       199, 418, 499, 353, 228, 371, 411, 385, 216, 446, 391, 407, 214,
       200, 324, 339, 461, 310, 386, 513, 404, 367, 335, 327])

In [15]:
rsupport

array([0.0798, 0.085 , 0.0746, 0.0836, 0.096 , 0.0876, 0.0382, 0.1108,
       0.046 , 0.0818, 0.0386, 0.0782, 0.0734, 0.0422, 0.0782, 0.076 ,
       0.0852, 0.0762, 0.092 , 0.0708, 0.0444, 0.0388, 0.0954, 0.064 ,
       0.0642, 0.0452, 0.0398, 0.0836, 0.0998, 0.0706, 0.0456, 0.0742,
       0.0822, 0.077 , 0.0432, 0.0892, 0.0782, 0.0814, 0.0428, 0.04  ,
       0.0648, 0.0678, 0.0922, 0.062 , 0.0772, 0.1026, 0.0808, 0.0734,
       0.067 , 0.0654])

In [37]:
def support(itemset, matrix):
    if len(itemset) == 0:
        return 0
    return sum(reduce((lambda x,y: x & y), [matrix[i] for i in itemset]))
    #occurence_col = matrix[itemset[0]]
    #for i in range(1, len(itemset)):
    #    occurence_col = occurence_col & matrix[itemset[i]]
    #return sum(occurence_col)

In [74]:
def supports(itemsets, matrix):
    supports_dict = {i: 0 for i in range(len(itemsets))}
    for idx in matrix.index:
        for i in range(len(itemsets)):
            itemset = itemsets[i]
            row = matrix.loc[idx]
            if reduce((lambda x,y: x&y), [row[item] for item in itemset]) == 1:
                supports_dict[i] += 1
    return supports_dict

In [75]:
supports([[0,1,2,3], [0], [1], [0,1], [0,1,2], [0,2]], bakery)

{0: 1, 1: 399, 2: 425, 3: 15, 4: 4, 5: 171}

In [ ]:
def candidateGen(set_list, k):
    C = []
    for f1 in set_list:
        for f2 in set_list:
            if len(f1 + f2) == len(f1) + 1:
                c = f1 + f2
                flag = True
                for 
                
    

In [67]:
def apriori(matrix, total_itemset, minSup):
    all_supports_dict = {}
    set_dict = {}
    all_supports_dict[1] = supports([[i] for i in total_itemset], matrix)
    set_dict[1] = [[i] for i in total_itemset]
    k = 2
    while(k <= len(total_itemset) and len(all_supports_dict[k-1].values()) > 0):
        

array([0., 0., 0., 0., 0., 0.])

In [83]:
supports([[i] for i in range(50)], bakery)

{0: 399,
 1: 425,
 2: 373,
 3: 418,
 4: 480,
 5: 438,
 6: 191,
 7: 554,
 8: 230,
 9: 409,
 10: 193,
 11: 391,
 12: 367,
 13: 211,
 14: 391,
 15: 380,
 16: 426,
 17: 381,
 18: 460,
 19: 354,
 20: 222,
 21: 194,
 22: 477,
 23: 320,
 24: 321,
 25: 226,
 26: 199,
 27: 418,
 28: 499,
 29: 353,
 30: 228,
 31: 371,
 32: 411,
 33: 385,
 34: 216,
 35: 446,
 36: 391,
 37: 407,
 38: 214,
 39: 200,
 40: 324,
 41: 339,
 42: 461,
 43: 310,
 44: 386,
 45: 513,
 46: 404,
 47: 367,
 48: 335,
 49: 327}